---
title: "codebook_pracc_gen"
author: "Miklos Bognar"
date: '2022 02 15 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(dplyr)
```
```{r}
data = data.frame(matrix(ncol = 7, nrow = 500))
names = c("id", "gender", "age", "branch", "stai1","stai2","stai3")
colnames(data) = names
```

```{r}
femaleprob = 0.49
maleprob = 0.49
otherprob = 0.02
data = data %>% 
  mutate(id = 1:500,
         age = sample(20:65, 500, replace = T),
         gender = sample(c('female','male','other'), 500, replace = T, prob = c(femaleprob, maleprob, otherprob)),
         branch = sample(c('science', 'engineering', 'manufacturing', 'human resources', 'security', 'management'), 500, replace = T, prob = c(0.1,0.35,0.35, 0.05, 0.05, 0.1)),
         stai1 = sample(1:7,500, replace = T),
         stai2 = sample(1:7,500, replace = T),
         stai3 = sample(1:7,500, replace = T))
```

```{r}
write.csv(data, "pharma_anxiety_study.csv", row.names = F)
```

